<a href="https://colab.research.google.com/github/difo23/BitacorasDataScienceDominicano/blob/master/T1_1_Numpy_Algebra_Lineal_BitacoraDataScienceDominicano.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bitácora de un Data Science Dominicano:
### NumPy y Álgebra lineal
* Itertools: Funciones que crean iteradores para un bucle eficiente
* Permutaciones y Combinaciones con itertools.
* ¿ Que es el álgebra lineal ?
* Aplicaciones del álgebra lineal.
* Matrices.
* Vectores.
* Transformación Lineal.
* Eigenvalues y Eigenvectors.
* Operaciones aritmeticas con matrices.
* Multiplicacion de matrices con el operador @.
* Librerias NumPy para algebra lineal 'numpy.linalg'.
* Transponer Matrices con NumPy.
* Matriz inversa con NumPy.
* Determinante y trazo.
* Multiplicacion punto.
* Proyecciones.




## [Itertools:](https://docs.python.org/3/library/itertools.html) Funciones que crean iteradores para un bucle eficiente

### Introducción a Itertools:

In [0]:
#Librería usada para trabajar con iteradores, utilidades para permutaciones y combinaciones.
import itertools as it

In [0]:
it.count?

In [0]:
#creo una variable itertools, que contiene un contador desde start=8, con pasos  step=8.
result_count = it.count(8, 8)

In [0]:
type(result_count)

itertools.count

In [0]:
# Puedo recorrer mi variable como un iterador , 
# si no limito el conteo hasta 60 sera infinito
for elemento in result_count:
  print(elemento)
  if elemento > 60:
    break

In [0]:
# Mi variable almacena la posicion de conteo. Ejemplo este resultado presentara
# un count(72,8) donde 72 representa el siguiente numero al salir del loop for
print(result_count)

count(72, 8)


In [0]:
# Otra funcion de Itertools es repeat, en este caso crea un iterador 
# con cinco 1's
result_repeat = it.repeat(1,5)

In [0]:
type(result_repeat)

itertools.repeat

In [0]:
# imprimo los cinco 1's por pantalla
for elemento in result_repeat:
  print(elemento)

1
1
1
1
1


In [0]:
# importo la libreria numpy, es recomendables importar todas las librerias
# que usaras al inicio de cada notebook
import numpy as np

In [0]:
# Puedo convertir el itertools obj en una lista comun.
arr = list(result_repeat)

In [0]:
arr

[1, 1, 1, 1, 1]

In [0]:
# Puedo crear un arreglo numpy con este resultado.
arr_numpy = np.array(arr)
arr_numpy

array([1, 1, 1, 1, 1])

### Producto cartesiano:

In [0]:
# itertools.product(*iterables, repeat=1)
# realiza el producto cartesiano entre el iterable str 'ABCD' y el iterable 'XYZ'
# Resp. conjunto de tuplas con cada operacion ('A', 'X'), ('A', 'Y') ...

result_product = it.product('ABCD', 'XYZ', repeat=1)

In [0]:
for element in result_product:
  print(element)

### Permutaciones:
Una permutación de un conjunto de elementos, es una disposición de dichos elementos teniendo en cuenta el orden. El número de permutaciones de “n” elementos tomados de “k” en “k” se calcula con itertools:


In [0]:
# permutaciones itertools.permutations(iterable, r=None)
result_permut= it.permutations(range(1,4))

In [53]:
for element in result_permut:
  print(element)

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


In [0]:
result_permut= it.permutations('ABC')

In [57]:
for element in result_permut:
  print(element)

('A', 'B', 'C')
('A', 'C', 'B')
('B', 'A', 'C')
('B', 'C', 'A')
('C', 'A', 'B')
('C', 'B', 'A')


In [0]:
result_permut= it.permutations('ABC', r= 2)

In [59]:
for element in result_permut:
  print(element)

('A', 'B')
('A', 'C')
('B', 'A')
('B', 'C')
('C', 'A')
('C', 'B')


### *Combinaciones*
Una combinación de un conjunto de elementos, es una selección de dichos elementos sin tener en cuenta el orden.

In [0]:
# itertools.combinations(iterable, r)
result_comb= it.combinations('ABC', r= 2)

In [63]:
for element in result_comb:
  print(element)

('A', 'B')
('A', 'C')
('B', 'C')


### Combinaciones con remplazo

In [0]:
# itertools.combinations_with_replacement(iterable, r)
result_comb_with_replacement= it.combinations_with_replacement('ABC', r= 2)

In [67]:
for element in result_comb_with_replacement:
  print(element)

('A', 'A')
('A', 'B')
('A', 'C')
('B', 'B')
('B', 'C')
('C', 'C')


### Ejercicios:

1. Eduardo, Carlos y Sergio se han presentado a un concurso de pintura. El concurso otorga 200 pesos al  primer  lugar  y 100 pesos al segundo. ¿De cuántas formas se pueden repartir los premios de primer y segundo lugar?


In [0]:
#creo un objeto iterable con los elementos a ordenar.

iter = ['Eduardo', 'Carlos', 'Sergio']

In [0]:
# notar que importa el orden de los elementos, asi que es una permutaciòn.
# r= 2 por los lugares del premio en cuestion.
result = it.permutations(iter, r=2)
arrx = []

In [81]:
for element in result:
  print(element)
  arrx.append(element)

('Eduardo', 'Carlos')
('Eduardo', 'Sergio')
('Carlos', 'Eduardo')
('Carlos', 'Sergio')
('Sergio', 'Eduardo')
('Sergio', 'Carlos')


In [83]:
result = len(arrx)
print('El numero de formas en que puedo repartir los premios es: ',result)

El numero de formas en que puedo repartir los premios es:  6


2.  Un chef va a preparar una ensalada de verduras con tomate, zanahoria, papa y brócoli. ¿De cuántas formas se puede preparar la ensalada usando solo 2 ingredientes?

In [0]:
iter = ['Tomate', 'Zanahoria', 'Papa', 'Brócoli']

In [0]:
# Aqui el orden no importa!
result = it.combinations(iter, r=2)
arrx = []

In [86]:
for element in result:
  print(element)
  arrx.append(element)

('Tomate', 'Zanahoria')
('Tomate', 'Papa')
('Tomate', 'Brócoli')
('Zanahoria', 'Papa')
('Zanahoria', 'Brócoli')
('Papa', 'Brócoli')


In [87]:
result = len(arrx)
print('El numero de formas en que puedo repartir las verduras es: ',result)

El numero de formas en que puedo repartir las verduras es:  6


3. ¿Cuántas fichas tiene el juego del dominó?

* Nota: Una ficha de dominó es un rectángulo en el que hay dos partes, en cada una de ellas hay una serie de puntos que indican la puntuación de esa parte. Estas puntuaciones van de blanca (0 puntos) a 6. Tenemos pares de puntuaciones de 0 a 6.

In [0]:
#Estas puntuaciones van de blanca (0 puntos) a 6
iter = ['0', '1', '2','3', '4', '5', '6']

In [0]:
#Una ficha de dominó es un rectángulo en el que hay dos partes, r=2 (partes)
result = it.combinations_with_replacement(iter, r=2)
arrx = []

In [96]:
for element in result:
  print(element)
  arrx.append(element)

('0', '0')
('0', '1')
('0', '2')
('0', '3')
('0', '4')
('0', '5')
('0', '6')
('1', '1')
('1', '2')
('1', '3')
('1', '4')
('1', '5')
('1', '6')
('2', '2')
('2', '3')
('2', '4')
('2', '5')
('2', '6')
('3', '3')
('3', '4')
('3', '5')
('3', '6')
('4', '4')
('4', '5')
('4', '6')
('5', '5')
('5', '6')
('6', '6')


In [98]:
result = len(arrx)
print('El numero de piezas de domino es: ',result)

El numero de piezas de domino es:  28


## [Numpy.linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html): Álgebra lineal

### Matrices usando NumPy

In [100]:
import numpy as np
# un arreglo de valores en columnas Cx y Filas Fx.
#  c0   c1
# [ 3,  5], f0
# [ 3,  7], f1
# [-4,  3]  f2
# una matrice fx por  cx, filas x columnas
# Un arreglo bidimensional en Numpy
arreglo_bidimensional = np.array([[3,5],[3,7],[-4,3]])
arreglo_bidimensional


array([[ 3,  5],
       [ 3,  7],
       [-4,  3]])

#### Operaciones con matrices

In [102]:
A = np.array([[3,5],[3,7],[-4,3]])
A

array([[ 3,  5],
       [ 3,  7],
       [-4,  3]])

In [104]:
B = np.array([[2,6],[2,4],[-4,1]])
B

array([[ 2,  6],
       [ 2,  4],
       [-4,  1]])

In [122]:
C = np.array([[9,3,2],[8,4,7]])
C

array([[9, 3, 2],
       [8, 4, 7]])

In [128]:
D = np.array([[9,3,2],[8,4,7],[1,3,2]])
D

array([[9, 3, 2],
       [8, 4, 7],
       [1, 3, 2]])

##### Suma de matrices

In [106]:
A+B

array([[ 5, 11],
       [ 5, 11],
       [-8,  4]])

In [107]:
B+A

array([[ 5, 11],
       [ 5, 11],
       [-8,  4]])

##### Resta de matrices:

In [108]:
A - B

array([[ 1, -1],
       [ 1,  3],
       [ 0,  2]])

In [109]:
B - A

array([[-1,  1],
       [-1, -3],
       [ 0, -2]])

##### Multiplicar por un escalar

In [110]:
10 * A

array([[ 30,  50],
       [ 30,  70],
       [-40,  30]])

##### Multiplicación de matrices
1. Matrices pueden ser multiplicadas solo si el numero de columnas en el fator de la izquierda es igual al numero de filas del factor de la derecha.
2.  Una matrix M x N multiplicada por una matriz N x P da como resultado una matrix M x P

In [138]:
A.shape


(3, 2)

In [139]:
B.shape

(3, 2)

In [130]:
C.shape

(2, 3)

In [131]:
D.shape

(3, 3)

In [133]:
C * A

ValueError: ignored

In [136]:
A * C

ValueError: ignored

In [137]:
A * B

array([[ 6, 30],
       [ 6, 28],
       [16,  3]])

In [126]:
C @ A

array([[28, 72],
       [ 8, 89]])

In [127]:
A @ C

array([[ 67,  29,  41],
       [ 83,  37,  55],
       [-12,   0,  13]])

In [132]:
A @ D

ValueError: ignored

In [140]:
D @ A

array([[28, 72],
       [ 8, 89],
       [ 4, 32]])

### Matrices Especiales con NumPy

#### Matrices Cero

In [142]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### Matrices Transpuestas

In [146]:
# Cambio la estructura de la matrix , 
# ejemplo una matrix 2 x 3 su transpuesta seria 3 x 2
C

array([[9, 3, 2],
       [8, 4, 7]])

In [152]:
C_t = C.transpose()
C_t

array([[9, 8],
       [3, 4],
       [2, 7]])

In [156]:
C

array([[9, 3, 2],
       [8, 4, 7]])

In [0]:
C_T = C.T

In [155]:
C_T

array([[9, 8],
       [3, 4],
       [2, 7]])

#### Matrices Simetricas