<a href="https://colab.research.google.com/github/difo23/BitacorasDataScienceDominicano/blob/master/T1_intro_Python_NumPy_BitacoraDSDominicano.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bitácoras de un Data Science Dominicano:  
##  Intro a Python y Numpy
[Más información sobre Numpy](https://numpy.org/)

    1. Importar librerias  y agregar alias.
    2. Usar ayuda en python y autocompletado.
    3. Python y sus caracteristicas principales.
        a.  Variables y tipos de datos en Python.
    4. ¿Por que usar Numpy?
        a.  Arreglos N-Dimensionales.
        b.  Diferencias entre el clasico array.array y los Numpy.array.
        c.  Atributo axis.

Mención especial a LaTex.
  

## 1. Importar librerías y agregar alias:

In [0]:
import numpy as np 
# Comentarios de una sola linea usan '#':
# np es el alias comun en el uso de numpy.
# En caso de no usar alias, tendrias que escribir 'numpy' 
# cada vez que uses la librería en este notebook.
""" 
Comentarios de varias lineas usan:
   Triple comilla doble para abrir el bloque de comentarios y 
    para cerrar el bloque.

"""


' \nComentarios de varias lineas usan:\n   Triple comilla doble para abrir el bloque de comentarios y \n    para cerrar el bloque.\n\n'

## 2. Usar ayuda en python y autocompletado:

In [0]:
# Para solicitar ayuda sobre un modulo o funcion solo tienes que terminar con el signo '?' de interrogación.
# Dirigete a la pestaña ayuda para obtener la información.
np?

In [0]:
np.array?

In [0]:
# Usando la tecla tab inicias la sugerencias de autocompletado. Con enter autocompletas.
np.shape

<function numpy.shape>

##  3.  Python y sus caracteristicas principales:
[Pagina Oficial de Python](https://www.python.org/doc/)
   *  [Tutorial Oficial de Pyhton en Español](http://docs.python.org.ar/tutorial/3/index.html)
   * Python es un lenguaje debilmente tipado   [Más info...](https://parzibyte.me/blog/2017/10/13/tipado-debil-tipado-fuerte-diferencias-explicacion/)
   * Python es un lenguaje interpretado [Más info...](https://blog.makeitreal.camp/lenguajes-compilados-e-interpretados/)
   * Python es un lenguaje multi paradigma [Más info...](http://www.4rsoluciones.com/blog/que-son-los-paradigmas-de-programacion-2/)
   * Todo en Python es un objeto. [Más info...](https://pythonista.io/cursos/py101/orientacion-a-objetos)

### Variables y tipos de datos en Python:

#### Tipos Basicos:

    * Números enteros.
    * Números de punto flotante.
    * Números complejos.
    * Iterables.
    * Strings.
    * Tuplas.
    * Listas.
    * Diccionarios.
   [Más info...](https://manuais.iessanclemente.net/index.php/Python_-_Tipos_de_datos)

In [0]:
# Creacion de un arreglo o lista normal de una sola dimensión.
arreglo_normal = [2, 0Xff, 0b111, False, True, 'hola', 12.25, [1,2], 
                  (2,4,5,"hola"), {'maria':12, 'Juana':15}]

In [0]:
# Busco ayuda sobre la funcion type()
type?

In [0]:
# Busco ayuda sobre la funcion len
len?

In [0]:
#Tamaño de un arreglo normal o list
len(arreglo_normal)

10

In [0]:
# Los arreglos en python pueden contener varios tipos de datos distintos
type_0 = type( arreglo_normal[0] )
type_1 = type( arreglo_normal[1] )
type_2 = type( arreglo_normal[2] )
type_3 = type( arreglo_normal[3] )
type_4 = type( arreglo_normal[4] )
type_5 = type( arreglo_normal[5] )
type_6 = type( arreglo_normal[6] )
type_7 = type( arreglo_normal[7] )
type_8 = type( arreglo_normal[8] )
type_9 = type( arreglo_normal[9] )


#Notar que creo un arreglo con parentesis en esta ocasion ¿ Cual es la diferencia con el arreglo_normal?
arreglo_type = (type_0, type_1, type_2, type_3, type_4, type_5, type_6, type_7, type_8, type_9)


In [0]:
arreglo_type

(int, int, int, bool, bool, str, float, list, tuple, dict)

In [0]:
type(arreglo_type)

tuple

In [0]:
# Tipo de datos de una variable
type(arreglo_normal)

list

In [0]:
# Recorrido del arreglo con los indices desde 0 a len(arreglo_normal) -1
# Uso el ciclo for.
for elemento in arreglo_normal:
  print(elemento)

2
255
7
False
True
hola
12.25
[1, 2]
(2, 4, 5, 'hola')
{'maria': 12, 'Juana': 15}


## 4. ¿Por qué  usar Numpy?
* Álgebra lineal: 
El álgebra lineal es una rama de las matemáticas que estudia conceptos tales como vectores, matrices, espacio dual, sistemas de ecuaciones lineales y en su enfoque de manera más formal, espacios vectoriales y sus transformaciones lineales. [Curso de Àlgebra Lineal en Khan Academy](https://es.khanacademy.org/math/linear-algebra)


### Arreglos N-Dimensionales:
 [Uso de LaTex](https://www.math.ubc.ca/~pwalls/math-python/jupyter/latex/)
* Matrices y Vectores
$$
\begin{matrix} 
a & b \\
c & d 
\end{matrix}
\quad
\begin{pmatrix} 
a & b \\
c & d 
\end{pmatrix}
\quad
\begin{bmatrix} 
a & b \\
c & d 
\end{bmatrix}
\quad
\begin{vmatrix} 
a & b \\
c & d 
\end{vmatrix}
\quad
\begin{Vmatrix} 
a & b \\
c & d 
\end{Vmatrix}
$$






  * Tablas 
      * Insertar imagenes.

![Ejemplo de tablas](https://www.monografias.com/trabajos91/prueba-hipotesis-f-fisher-empleando-excel-y-winstats/image011.png)

 
### Diferencias entre el clasico array.array y los Numpy.array:
[Más información](https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference)
*  Tamaño: las estructuras de datos de Numpy ocupan menos espacio
*  Rendimiento: son más rápidos en termino de acceso a datos que las listas
*  Funcionalidad: SciPy y NumPy tienen funciones optimizadas, como las operaciones de álgebra lineal integradas.

In [0]:
#vamos a crear un arreglo numpy de 1 dimension

arreglo_numpy = np.array([3,4,4.5, 'Hola', -3])

In [0]:
arreglo_numpy
# Nota como el tipo de los elementos cambia de tipo en Numpy, todos los 
# elementos del arreglo son unicode strings
# dtype='<U32'

array(['3', '4', '4.5', 'Hola', '-3'], dtype='<U32')

In [0]:
arreglo_numpy = np.array([3, 4.5, 5, 6])
arreglo_numpy
# Nota como todos los elementos del array cambian a float
# podemos decir que numpy trabaja con arreglos de un solo tipo de datos.

array([3. , 4.5, 5. , 6. ])

In [0]:
arreglo_numpy[0]
#Los arreglos en numpy se recorren igual que los arreglos clasicos.

3.0

In [0]:
type(arreglo_numpy)

numpy.ndarray

In [0]:
type(arreglo_numpy[0])
#nota que los tipos ahora son tipos especiales de numpy

numpy.float64

In [0]:
# para saber la dimensiones que tiene un array numpy
arreglo_numpy.ndim

1

In [0]:
arreglo_numpy.shape 
# Nos permite ver la forma de nuestro arreglo tiene 4, retorna una tupla

(4,)

In [0]:
arreglo_numpy.size
# la cantidad de lementos

4

In [0]:
# Crear un arrglo bidimensional
arreglo_bidimensional = np.array([[1,'Hola'],[3,7],[-1,5]])
arreglo_bidimensional
# volvemos a ver el cambio de tipo pero esta vez a '<U21'

array([['1', 'Hola'],
       ['3', '7'],
       ['-1', '5']], dtype='<U21')

¿Por qué uno de los array es del tipo '<U32' y el otro es  '<U21'?
* [Significado de los Numpy type](http://lagrange.univ-lyon1.fr/docs/numpy/1.11.0/reference/arrays.dtypes.html)
*[Big-Endian y Little-Endian
](https://www.arumeinformatica.es/blog/los-formatos-big-endian-y-little-endian/)

In [0]:
# Crear un arrglo bidimensional
arreglo_bidimensional = np.array([[3,5],[3,7],[-4,3]])
arreglo_bidimensional

array([[ 3,  5],
       [ 3,  7],
       [-4,  3]])

In [0]:
arreglo_bidimensional.shape

(3, 2)

In [0]:
arreglo_bidimensional.ndim

2

In [0]:
arreglo_bidimensional.size

6

In [0]:
# Recorrer Numpy 2 dimension array
#  c0   c1
# [ 3,  5], f0
# [ 3,  7], f1
# [-4,  3]  f2
#arreglo_bidimensional[fx, cx]
arreglo_bidimensional[2, 1]
# toma el elemento en fila 2 y la columna 1, en este caso el resultado es 3

3

In [0]:
# 0:3 es un rango que va de 0, 1 y 2 no llega a 3,
#este recorre las 3 filas en la columna 0
arreglo_bidimensional[0:3, 0]


array([ 3,  3, -4])

In [0]:
#retorna todo el arreglo
arreglo_bidimensional[0:3, 0:2]

array([[ 3,  5],
       [ 3,  7],
       [-4,  3]])

In [0]:
col0 = arreglo_bidimensional[0:3, 0]
col0

array([ 3,  3, -4])

In [0]:
col0.shape

(3,)

In [0]:
# Cambia la estructura de la columna, transfomandola  a 3 filas y una columana
col0 = col0.reshape(3,1)

In [0]:
col0

array([[ 3],
       [ 3],
       [-4]])

In [0]:
col0.shape

In [0]:
col0 = col0.reshape(1,3)
col0
#nota que el arreglo esta dentro de otro arreglo.

array([[ 3,  3, -4]])

In [0]:
col0.shape

(1, 3)

In [0]:
array_complejos = np.array( [ [1,2], [3,4] ], dtype=complex )
array_complejos

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [0]:
#Arreglo completo de zeros
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
# crear un arreglo de 3 dim con 1`s tipo int16
array_ones = np.ones( (2,3,4), dtype=np.int16 ) 

In [0]:
array_ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [0]:
array_ones.ndim

3

In [0]:
#crea array vacio
np.empty( (2,3) )  

In [0]:
#Crea un arreglo de una dim con los numeros del 5 al menor que 30 con pasos de 5 en 5
np.arange( 10, 30, 5 )


array([10, 15, 20, 25])

# Fin...